services:
  # Servizio per l'app NestJS
  api-gateway:
    build: .
    container_name: ApiGateway
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - TZ=Europe/Rome
    networks:
      - my-custom-backend